### ISSUE TITLE
[FEAT] 마이페이지 사이드바, 프로필 구현

### ISSUE THREAD

**Issue by geunu97** [Totee-Side-Project/totee-fe#136]
## 📌  개요

- 마이페이지 사이드바 구현
- 마이페이지 사용자 프로필 구현

<br>

## 💻  기능 설명

- 사이드바에서 메뉴 클릭 시 해당 컴포넌트를 렌더링합니다.
- 프로필은 기본적으로 렌더링합니다.
- 프로필에서 사용자 정보(닉네임, 역할, 포지션, 소개, 진행중인 스터디 갯수, 진행중인 멘토링 갯수)를 보여줍니다.
- 사용자가 멘토일 경우에만 totee 뱃지를 보여줍니다.
- 프로필 수정 작업 시 
  - 닉네임은 2글자 이상 5글자 이하만 입력할 수 있습니다.
  - 소개는 120글자이하만 입력할 수 있습니다.
  - 닉네임 작업 수정 후 -> 수정하기 버튼 클릭 시 -> 닉네임 중복 검사 API 요청 후 성공하면 바로 사용자 정보 업데이트 API 요청을 합니다.

<br>

## ✅  참고 사항

- 마이페이지에서 헤더와 푸터를 제거하였습니다.
- 모든 곳에 타입을 선언하지 않고, 타입 추론이 안되는 곳에 타입 선언을 하였습니다.
- 에러 처리(닉네임 중복 검사 API 요청 실패, 사용자 정보 업데이트 API 요청 실패)시 alert으로 처리하였습니다.
- 로딩 처리는 필요할 것 같지 않아서 하지 않았습니다.
- 추후 필요하다면 에러, 로딩 처리를 suspense, error boundary를 활용할 수 있도록 고민해보겠습니다.
- 추후 모바일 뷰 작업 필요합니다.

<br>

## 📷  스크린 샷
![1](https://user-images.githubusercontent.com/73439375/212734771-aacbf14a-9cbd-4dbe-abb6-0b4d900aeaf3.png)
![3](https://user-images.githubusercontent.com/73439375/212734328-98ac4283-5dab-41eb-9ab3-baf86fdb1a99.png)
![5](https://user-images.githubusercontent.com/73439375/212734572-c3454465-d83d-48bf-b73c-94c5875bc67e.png)

**Comment by rnjstmdals6** [comment]
참여중인 스터디 목록을 반환하는 api는 제작 예정에 있습니다! 최대한 빨리 제작해서 배포해놓겠습니다.
다른 기능을 우선으로 작업 부탁드릴게요 !! :)
