### ISSUE TITLE
[FEAT] 좋아요 기능을 개발합니다

### ISSUE THREAD

**Issue by ctaaag** [Totee-Side-Project/totee-fe#21]
## 📌  개요

좋아요 기능을 개발합니다

<br>

## 💻  기능 설명

- 좋아요 클릭 시 백엔드 데이터 전송 좋아요 수 +1 해서 전송
- 좋아요가 눌러진 게시글은 빨간색 하트
- 좋아요 버튼을 한 번 더 클릭하면 좋아요 해제

<br>

## ✅  참고 사항

- [x] react-query 활용해서 좋아요 데이터 활용하기

- [x] 마크업 하기

<br>

## 📷  스크린 샷
<img width="1071" alt="스크린샷 2022-07-16 오후 10 11 02" src="https://user-images.githubusercontent.com/103479322/179356300-55e139bf-cc61-4067-a525-9a0c8cad460c.png">

**Comment by rnjstmdals6** [comment]
- 좋아요 클릭 시 백엔드 데이터 전송 좋아요 수 +1 해서 전송
POST 요청 시 좋아요 수 + 1해서 안보내주셔도 돼요!
/api/v1/post/like/{postId} <- 하고 헤더에 토큰 담아서 보내주시면 됩니다

**Comment by ctaaag** [comment]
호오 알겠습니다! 해보다가 막히는 부분 있으면 물어보겠습니다 :)
