### ISSUE TITLE
[FEAT] 추천카드리스트 기능 개발

### ISSUE THREAD

**Issue by ctaaag** [Totee-Side-Project/totee-fe#28]
## 📌  개요

- 추천카드리스트 기능 개발

<br>

## 💻  기능 설명

- [x] eact-query로 api fetch 구조 설계
- [x] 각 화면의 내용은 추천게시물 api에서 가져오기
- [x] 해당 화면의 카드 클릭시 해당 게시물로 이동
- [x] 좌우버튼 클릭시 게시물 변경 (추천 게시물 끝날 때 까지?)
- [x] 모든 목록을 다 봤으면 어떻게 할지 구상(그냥 안넘어가게 하기?)

<br>

## ✅  참고 사항

- 추천게시물 api 연동하기
- react-material-ui-carousel 라이브러리 활용해서 슬라이더 기능 구현
- https://learus.github.io/react-material-ui-carousel/

<br>

## 📷  스크린 샷
<img width="312" alt="스크린샷 2022-07-21 오후 9 10 50" src="https://user-images.githubusercontent.com/103479322/180210394-7c2e0140-079b-48b8-8ca7-ddbf209be256.png">
<img width="1648" alt="스크린샷 2022-07-21 오후 9 12 38" src="https://user-images.githubusercontent.com/103479322/180210872-a8815406-6aec-4602-bcb8-d2489b391d29.png">

**Comment by aeong98** [comment]
모든 목록을 다 봤으면 어떻게 할지 구상(그냥 안넘어가게 하기?)

-> MaterialUI Carousel 라이브러리에서 마지막 목록 다음에 안넘어가는것이 아니라, **다시 처음 목록으로 넘어가게 할 수** 있는 것같아요! 뭔가 디폴트로 들어가있는 기능같은데 이대로 구현하면 좋지않을까요?!

**Comment by ctaaag** [comment]
호오 알겠습니다! 좋은 의견 감사해요 :)
