### ISSUE TITLE
[BUG] 최초 카카오 소셜 로그인 시 로그인 요청 관련 에러

### ISSUE THREAD

**Issue by ahn0min** [Totee-Side-Project/totee-fe#87]
### 실패
- 카카오 소셜 로그인 최초 시도 시 닉네임, 프로필이미지, 포지션을 입력 서버로 요청을 보낸다.
- bad request (400) 으로 응답이 넘어오고 더 이상 진행되지 않는 문제가 발생
- 닉네임: kakao, 이미지파일 확장자: .png

### 성공
- 닉네임과 파일을 변경하니 요청이  성공되었다.
- 닉네임: aym2, 이미지파일 확장자: .png
<br>

### 왜 실패를 하는걸까?
닉네임의 길이도 제한된 길이인 6글자를 넘지않았고, 이미지파일 확장자도 동일한 .png였음에도 첫번째 케이스에서는 왜 400으로 응답이 넘어오는지 잘 모르겠습니다.
 왜 그런지 예상되는 부분이 있으신가요??

## ✅  해결 방법
- 버그를 어떻게 해결했는지 적어주세요.
1. 원인
2. 방법
3. 결과

<br>

### 실패 케이스
![image](https://user-images.githubusercontent.com/89904226/203221033-49bac21a-1fff-4253-a15a-08d9278da915.png)

### 성공 케이스
![image](https://user-images.githubusercontent.com/89904226/203221073-0d410f4b-9d39-49a2-91bb-0988200b4058.png)

<br>

## ⭐ 추가 내용
- 문제를 해결하는 데 참고했던 자료의 링크를 공유해주세요.

**Comment by rnjstmdals6** [comment]
이 부분은 Enum 타입 매칭이 안되어 발생한 오류였습니다.
지금은 수정하여 정상 작동합니다.
